Repository won-won-smart-parking/smart-parking-fe, pull requests merged in 2025-08, with the labels that each got.

#42 [ Refactor ] - 전역 스타일(global.css) 경로 이동 및 Metro 설정 수정 Close #41
  metro.config.js
  src/app/_layout.tsx
  src/global/styles/global.css
  tsconfig.json
Labels: refactor

#45 [ Feature ] - Atom / Tag Close #34
  src/app/index.tsx
  src/shared/ui/atoms/tag/index.tsx
  src/shared/ui/atoms/tag/variants.ts
Labels: feature

#49 [ Refactor ] - 디자인 토큰 수정 Fix #46
  app.json
  src/app/index.tsx
  src/shared/tokens/color.ts
  src/shared/tokens/elevation.ts
  src/shared/tokens/font-size.ts
  src/shared/tokens/index.ts
  src/shared/tokens/spacing.ts
  src/shared/tokens/typography.ts
  src/shared/tokens/typography/Text.tsx
  src/shared/tokens/typography/variants.ts
  tailwind.config.js
Labels: bug, refactor

#51 [ Refactor ] - Atom / Text Fix #50
  .husky/pre-push
  src/app/index.tsx
  src/shared/ui/atoms/tag/index.tsx
  src/shared/ui/atoms/text/index.tsx
Labels: refactor

#52 [ Refactor ] - pre-push 브랜치 패턴 수정
  .husky/pre-push
Labels: refactor

#53 [ Docs ] - 프로젝트 가이드 라인 문서 정리 #10
  README.md
  docs/README.md
  docs/bookmark/README.md
  docs/convention/README.md
  docs/convention/code.md
  docs/convention/directory_structure.md
  docs/convention/git.md
  docs/dev_guide/README.md
  docs/dev_guide/atom.md
  docs/dev_guide/design-token.md
  docs/guides/README.md
  docs/guides/branch_management.md
  src/app/index.tsx
  src/global/styles/nativewind-interop.ts
  src/shared/ui/atoms/icon/index.tsx
Labels: docs

#54 [ Feature ] - Atom / Button Close #27
  .prettierrc
  src/shared/tokens/elevation.ts
  src/shared/ui/atoms/button/content.tsx
  src/shared/ui/atoms/button/foundation/a11y.ts
  src/shared/ui/atoms/button/foundation/index.ts
  src/shared/ui/atoms/button/foundation/style.ts
  src/shared/ui/atoms/button/foundation/variant.ts
  src/shared/ui/atoms/button/index.tsx
Labels: feature

#58 [ Feature ] - Atom / Radio Close #36
  src/shared/ui/atoms/radio/index.tsx
Labels: feature

#59 [ Feature ] - Atom / Checkbox Close #38
  src/shared/ui/atoms/checkbox/index.tsx
Labels: feature

#61 [ Feature ] - Atom / Input Close #32
  src/shared/tokens/spacing.ts
  src/shared/ui/atoms/input/foundation/index.ts
  src/shared/ui/atoms/input/index.tsx
  src/shared/ui/atoms/input/part/ClearButton.tsx
  src/shared/ui/atoms/input/variant/SearchInput.tsx
  src/shared/ui/atoms/input/variant/UnderlineInput.tsx
  src/shared/ui/atoms/input/variant/index.ts
Labels: feature

#62 [ Feature ] - Atom / Tab Close #39
  babel.config.js
  package.json
  src/app/(tabs)/_layout.tsx
  src/app/(tabs)/bookmark.tsx
  src/app/(tabs)/index.tsx
  src/app/(tabs)/profile.tsx
  src/app/(tabs)/ticket/_layout.tsx
  src/app/(tabs)/ticket/daily.tsx
  src/app/(tabs)/ticket/regular.tsx
  src/app/_layout.tsx
  src/app/auth/_layout.tsx
  src/app/auth/reset-password.tsx
  src/app/auth/sign-in.tsx
  src/app/auth/sign-up.tsx
  src/app/index.tsx
  src/app/payment/.gitkeep
  src/app/profile/_layout.tsx
  src/app/profile/car/[carId].tsx
  src/app/profile/car/create.tsx
  src/app/profile/car/index.tsx
  src/app/profile/delete.tsx
  src/app/profile/edit.tsx
  src/app/profile/setting.tsx
  src/app/search/.gitkeep
  src/app/service/.gitkeep
  src/app/ticket/[passId].tsx
  src/app/ticket/_layout.tsx
  src/app/ticket/history/_layout.tsx
  src/app/ticket/history/daily.tsx
  src/app/ticket/history/regular.tsx
  yarn.lock
Labels: feature

#66 [ Feature ] - Atom / Avatar Close #26
  src/shared/ui/atoms/avatar/avatar-styles.ts
  src/shared/ui/atoms/avatar/index.tsx
Labels: feature

#69 [ Bug ] - 의존성 보안 취약점 Close #68
  audit-ci.jsonc
Labels: bug

#75 [ Docs ] - 프로젝트 가이드 라인 문서 정리
  docs/README.md
  docs/convention/README.md
  docs/convention/env.md
  docs/workflows/commit-msg.md
  docs/workflows/feature_workflow.md
Labels: docs

#76 [ Refactor ] - Zod 환경 변수 검증 Fix #70
  .github/workflows/pull-ci.yml
  .husky/pre-push
  package.json
  scripts/env-check/index.ts
  scripts/env-check/mode.ts
  scripts/env-check/report.ts
  scripts/env-check/schema.ts
  scripts/env-check/schemas/index.ts
  scripts/env-check/schemas/private.ts
Labels: refactor

#98 [ Bug ] - Nativewind 초기화 실패 + 파일 간 순환 참조 경고 문구 Fix #97
  src/app/_layout.tsx
  src/global/styles/global.css
  src/global/styles/nativewind-interop.ts
  src/global/types/svg.d.ts
  src/shared/ui/atoms/avatar/index.tsx
  src/shared/ui/atoms/button/variant/BothButton.tsx
  src/shared/ui/atoms/button/variant/IconButton.tsx
  src/shared/ui/atoms/button/variant/LabelButton.tsx
  src/shared/ui/atoms/checkbox/index.tsx
  src/shared/ui/atoms/chip/variant/BothChip.tsx
  src/shared/ui/atoms/chip/variant/IconChip.tsx
  src/shared/ui/atoms/chip/variant/LabelChip.tsx
  src/shared/ui/atoms/floating-button/variant/ExtendedFloatingButton.tsx
  src/shared/ui/atoms/floating-button/variant/IconFloatingButton.tsx
  src/shared/ui/atoms/input/part/ClearButton.tsx
  src/shared/ui/atoms/input/variant/UnderlineInput.tsx
  src/shared/ui/atoms/select/index.tsx
  src/shared/ui/atoms/social-button/index.tsx
  src/shared/ui/atoms/tag/index.tsx
  tsconfig.json
Labels: bug

#99 [ Feature ] - Molecular / Button Group Close #85
  src/shared/ui/atoms/button/variant/IconButton.tsx
  src/shared/ui/molecules/button-group/index.tsx
Labels: feature

#101 [ Feature ] - Molecular / FAB Group Close #83
  src/widgets/map/floating-button-group/index.tsx
Labels: feature

#102 [ Feature ] - Molecular / Filter Group Close #87
  src/shared/ui/atoms/chip/foundation/preset.ts
  src/shared/ui/atoms/chip/variant/BothChip.tsx
  src/shared/ui/atoms/chip/variant/IconChip.tsx
  src/shared/ui/atoms/chip/variant/LabelChip.tsx
  src/widgets/filter-group/index.tsx
  src/widgets/filter-group/variant/LabelFilterGroup.tsx
  src/widgets/filter-group/variant/ScrollFilterGroup.tsx
  src/widgets/filter-group/variant/SortFilterGroup.tsx
  src/widgets/filter-group/variant/index.ts
Labels: feature

#105 [ Feature ] - Molecular / User Profile Close #86
  src/shared/ui/molecules/user-profile/index.tsx
Labels: feature

#107 [ Feature ] - Molecular / Profile Uploader Close #96
  src/shared/ui/molecules/profile-uploader/index.tsx
Labels: feature

#108 [ Feature ] - Molecular / Summary Card Close #94
  src/entities/payment/ui/molecules/summary-card/index.tsx
  src/entities/payment/ui/molecules/summary-card/part/PaymentSummaryItem.tsx
Labels: feature

#111 [ Feature ] - Molecular / Input Field Close #95
  src/shared/ui/atoms/input/foundation/index.ts
  src/shared/ui/atoms/input/variant/SearchInput.tsx
  src/shared/ui/atoms/input/variant/UnderlineInput.tsx
  src/shared/ui/molecules/input-field/index.tsx
  src/shared/ui/molecules/input-field/part/HelperText.tsx
  src/shared/ui/molecules/input-field/part/TextInput.tsx
  src/shared/ui/molecules/input-field/part/index.ts
Labels: feature

#114 [ Feature ] - Molecular / List Item Close #82
  src/shared/ui/atoms/switch/index.tsx
  src/shared/ui/molecules/list-item/index.tsx
  src/shared/ui/molecules/list-item/variant/DefaultListItem.tsx
  src/shared/ui/molecules/list-item/variant/NavigationListItem.tsx
  src/shared/ui/molecules/list-item/variant/SelectableListItem.tsx
  src/shared/ui/molecules/list-item/variant/SwitchListItem.tsx
  src/shared/ui/molecules/list-item/variant/ValueListItem.tsx
  src/shared/ui/molecules/list-item/variant/index.ts
Labels: feature
